### ISSUE TITLE
GPU available, but not found by discoart

### ISSUE THREAD

**Issue by randyg3000** [jina-ai/discoart#4]
System is NVIDIA Jetson Orin

GPU is enabled, and OpenCV finds it with a trivial Python example which I can provide if needed:

['NVIDIA CUDA: YES (ver 11.4, CUFFT CUBLAS FAST_MATH)', 'NVIDIA GPU arch: 53 62 72 87', 'NVIDIA PTX archs:', 'cuDNN: YES (ver 8.0)']

However, discoart does not?

RuntimeError: CUDA is not available. DiscoArt is unbearably slow on CPU. Please switch to GPU device, if you are using Google Colab, then free tier would work.

Suspect this is possibly Pytorch not happy about the driver v. cuda version?

**Comment by hanxiao** [comment]
Yeah, im not sure NVIDIA Jetson Orin is correctly set up there? Did you successfully run other GPU code before DiscoArt, for example, simple CNN on PyTorch website?

**Comment by randyg3000** [comment]
the problem was the pytorch setup, thanks for looking at this

**Comment by KnoBuddy** [comment]
> > the problem was the pytorch setup, thanks for looking at this
> 
> What specifically did you do to fix the pytorch setup?

Use the appropriate shell command from [HERE](https://pytorch.org/)
